apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
  interval: 5m
  releaseName: tf-controller
  targetNamespace: flux-system
  values:
    runner:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::656627883778:policy/tf-controller