apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: branch-planner-demo
  namespace: flux-system
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  backendConfig:
    customConfiguration: |
      backend "s3" {
        encrypt = true    
        bucket = "eng2023-tf-state"
        dynamodb_table = "terraform-state-lock-dynamo"
        key    = "terraform.tfstate"
        region = "eu-west-1"
      }
  path: ./
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: branch-planner-demo
    namespace: flux-system