apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    solvers:
    - selector:
        dnsZones:
          - "save-it.co.uk"
      dns01:
        route53:
          region: eu-west-1
          hostedZoneID: Z00114353FRO5DCSYJTJ7