---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart:
    spec:
      version: "1.11.0"
  values:
    registry: txt
    txtOwnerId: "Z00114353FRO5DCSYJTJ7"
    txtPrefix: "eng-ext-dns"
    domainFilters: ["save-it.co.uk"]
