---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-lb-controller
  namespace: kube-system
spec:
  interval: 60m0s
  path: ../../overlays/cluster-a/kube-system/aws-lb-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system