apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/cluster-a/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system