---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-monitor
  namespace: kube-system
spec:
  interval: 60m0s
  path: ../../overlays/cluster-a/service-monitors
  prune: true
  dependsOn:
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
