---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform-controller
  namespace: kube-system
spec:
  interval: 60m0s
  path: ../../overlays/cluser-a/tf-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
