---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-lb-controller
  namespace: kube-system
spec:
  chart:
    spec:
      version: "1.4.5"
  values:
    serviceAccount:
      create: true
    clusterName: cluster-a
